/**
 * Seed TeacherRecruitment records from MWED / UL-Mankweng Circuit WSP documents.
 * Data sourced from: Excel spreadsheet + scanned CVs, IDs, application letters,
 * SARS documents and certificates read via vision extraction (2026-06-02).
 *
 * Teachers without full names in docs are seeded with null firstName — update manually.
 */
const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();
const SCHOOL_ID = 'school-hartrog-001';

// S = SUBMITTED, O = OUTSTANDING, N = NOT_APPLICABLE
const S = 'SUBMITTED', O = 'OUTSTANDING', N = 'NOT_APPLICABLE';

const TEACHERS = [
  // ── BURGHERSDORP ────────────────────────────────────────────────────────────
  {
    lastName: 'Letjeku', firstName: null, initials: 'KD',
    idNumber: '0207300798080', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Burghersdorp',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: O, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Moloisi', firstName: null, initials: 'MS',
    idNumber: '9403240933082', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Burghersdorp',
    cvStatus: O, saceCertStatus: S, saceNumber: '12478558',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: O, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Peu', firstName: null, initials: 'MA',
    idNumber: '8709240697084', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Burghersdorp',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Nkwinika', firstName: 'Gail Ntumbuluko', initials: 'GN',
    idNumber: '9907150225081', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Burghersdorp',
    cvStatus: S, saceCertStatus: S, saceNumber: '12822771',
    matricCertStatus: S, qualCertStatus: N, bankLetterStatus: N,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: N,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE',
  },
  {
    lastName: 'Shivambu', firstName: 'Rikhandzu', initials: 'R',
    idNumber: '9910250704088', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Burghersdorp',
    cvStatus: S, saceCertStatus: S, saceNumber: '12762349',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE',
  },

  // ── KGAPANE HS ──────────────────────────────────────────────────────────────
  {
    lastName: 'Maake', firstName: null, initials: 'ML',
    idNumber: '9306021084084', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '12495931',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Malematsa', firstName: null, initials: 'TM',
    idNumber: '0107180885082', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Raphadu', firstName: 'Mmatsie Caron', initials: 'MC',
    idNumber: '9302200334085', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE',
  },
  {
    lastName: 'Rasebotsa', firstName: 'Sekhutlo Tumiso', initials: 'ST',
    idNumber: '9302060822088', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '12681646',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE',
  },
  {
    lastName: 'Setati', firstName: 'Kgadi Peter', initials: 'KP',
    idNumber: '9409275822082', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: 'Copy of ID and/or other documents are not clearly legible',
  },
  {
    lastName: 'Kgahamedi', firstName: null, initials: 'C',
    idNumber: null, gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: O, qualCertStatus: O, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Baloyi', firstName: null, initials: 'R',
    idNumber: '9308086168083', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: O, qualCertStatus: O, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Mokalapa', firstName: null, initials: 'LMY',
    idNumber: null, gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: O, saceCertStatus: O, saceNumber: null,
    matricCertStatus: O, qualCertStatus: O, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Mashale', firstName: null, initials: 'JM',
    idNumber: null, gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Kgapane HS',
    cvStatus: O, saceCertStatus: O, saceNumber: null,
    matricCertStatus: O, qualCertStatus: O, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },

  // ── PHUSELA HS ──────────────────────────────────────────────────────────────
  {
    lastName: 'Maake', firstName: 'Neptune Mahlatse', initials: 'NM',
    idNumber: '8704280503086', gender: null, raceGroup: 'AFRICAN',
    phone: '0729484324', email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics / Physical Sciences',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: '3958027165', proofOfResidenceStatus: S,
    hasMathematicsMatric: true, hasMathematicsMajor: true,
    comments: 'Copy of ID and/or other documents are not clearly legible. 12 years teaching Mathematics & Physical Sciences.',
  },
  {
    lastName: 'Makondo', firstName: 'Fikile Precious', initials: 'FP',
    idNumber: '9409030594083', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: '0822694551', email: 'fikilemakondo@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics / Physical Sciences',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '12765231',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: true, hasMathematicsMajor: true,
    comments: 'B.Ed Mathematics & Physical Sciences, University of Venda (2016–2022).',
  },
  {
    lastName: 'Malatji', firstName: 'Peter Mokete', initials: 'MP',
    idNumber: '7201016958081', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: '0722566019', email: 'moketepm9@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics',
    applicationDate: new Date('2026-05-12'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '262443',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: '1601318148', proofOfResidenceStatus: O,
    hasMathematicsMatric: true, hasMathematicsMajor: true,
    comments: 'HoD Mathematical Sciences (CS2), Phusela High School. Persal: 81509375.',
  },
  {
    lastName: 'Maphaba', firstName: null, initials: 'MH',
    idNumber: '8709051242087', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'English / Life Orientation',
    applicationDate: new Date('2026-04-21'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '11167160',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics pass at Matric & no Mathematics major at HE. 9 years teaching experience. B.Ed University of Venda (English FAL & Sepedi HL).',
  },
  {
    lastName: 'Mohale', firstName: null, initials: 'MB',
    idNumber: '6608200469082', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Life Sciences / Natural Sciences',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE. 38 years teaching Life Sciences & Natural Sciences.',
  },
  {
    lastName: 'Phukubye', firstName: 'Mahlatse', initials: 'M',
    idNumber: '9501046088082', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: '0726685502', email: 'hiatze0630701197@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics / Physical Sciences',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: true, hasMathematicsMajor: true,
    comments: 'BSc University of Venda; PGCE University of Johannesburg.',
  },
  {
    lastName: 'Raswiswi', firstName: 'Mpho Fanie', initials: 'MF',
    idNumber: '9101166224086', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: '0837314220', email: 'Raswiswimpho@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: S, saceNumber: '12333747',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: true, hasMathematicsMajor: null,
    comments: 'Note: Excel had ID as 9191166224086 — document-verified ID is 9101166224086.',
  },
  {
    lastName: 'Sephoto', firstName: 'Zanele Maria', initials: 'ZM',
    idNumber: '9601290404082', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'English / Life Orientation',
    applicationDate: new Date('2026-04-22'),
    school: 'Phusela HS',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE. 2 years experience teaching English & Life Orientation.',
  },

  // ── MAFUTSANE ───────────────────────────────────────────────────────────────
  {
    lastName: 'Majokoja', firstName: 'Phokele Patrick', initials: 'PP',
    idNumber: '6911305569081', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: '0822133655', email: 'majokojaphokelepatrick@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Mafutsane',
    cvStatus: S, saceCertStatus: S, saceNumber: '1097271',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: '565897170', proofOfResidenceStatus: O,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE.',
  },
  {
    lastName: 'Makwela', firstName: 'Molope Joel', initials: 'MJ',
    idNumber: '7401315353089', gender: 'MALE', raceGroup: 'AFRICAN',
    phone: '0825753095', email: 'makwelmj31@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Mafutsane',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: '0326046158', proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: 'Copy of ID and/or other documents are not clearly legible.',
  },
  {
    lastName: 'Mohosana', firstName: 'Mamoloko Linah', initials: 'ML',
    idNumber: '8605040888081', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: '0661579850', email: 'linahcandy@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Mafutsane',
    cvStatus: S, saceCertStatus: S, saceNumber: '12508806',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: '0418276176', proofOfResidenceStatus: S,
    hasMathematicsMatric: false, hasMathematicsMajor: false,
    comments: 'No Mathematics at Matric & no Mathematics major at HE.',
  },
  {
    lastName: 'Mudau', firstName: 'Mokgadi Pertunia', initials: 'MP',
    idNumber: '8410120965085', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: '0730298983', email: 'mokgadimokgosi@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Mafutsane',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: '830128278', proofOfResidenceStatus: S,
    hasMathematicsMatric: true, hasMathematicsMajor: null,
    comments: 'Matric subjects include Mathematics (Mathibadifate High School, 2006).',
  },
  {
    lastName: 'Phalane', firstName: 'Mmatapa Phyllis', initials: 'MP',
    idNumber: '7611020313083', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: '0782200022', email: 'phillisphalane@gmail.com',
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Science Education',
    applicationDate: new Date('2026-04-22'),
    school: 'Mafutsane',
    cvStatus: S, saceCertStatus: S, saceNumber: '218847',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: '0977111152', proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: 'ID was marked Outstanding in Excel — verified from CV & SARS doc: 7611020313083. B.Ed Honours (UL). ACE Science Education.',
  },

  // ── PHEREHLA MAAKE ──────────────────────────────────────────────────────────
  {
    lastName: 'Hlanwini', firstName: null, initials: 'TM',
    idNumber: '6612110511082', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: S, saceNumber: '1043921',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Kgatle', firstName: null, initials: 'MP',
    idNumber: '8703010846088', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: S, saceNumber: '12225763',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Magagule', firstName: null, initials: 'MS',
    idNumber: '7609230437080', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: S, saceNumber: '1019100',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: S,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Mashabane', firstName: null, initials: 'KM',
    idNumber: '6710165577089', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: S, saceNumber: '16226',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: null,
  },
  {
    lastName: 'Ramaselela', firstName: null, initials: 'MP',
    idNumber: '9911050585081', gender: null, raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Mathematics', applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: O, saceNumber: null,
    matricCertStatus: O, qualCertStatus: O, bankLetterStatus: O,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: 'Most documents outstanding.',
  },
  {
    lastName: 'Shai', firstName: 'Mapula Sarah', initials: 'MS',
    idNumber: '6709260532080', gender: 'FEMALE', raceGroup: 'AFRICAN',
    phone: null, email: null,
    postAppliedFor: 'Grade 8 & 9 Mathematics Teacher',
    subjectSpecialization: 'Education Management',
    applicationDate: new Date('2026-04-22'),
    school: 'Pherehla Maake',
    cvStatus: S, saceCertStatus: S, saceNumber: '1180647',
    matricCertStatus: S, qualCertStatus: S, bankLetterStatus: S,
    sarsDocStatus: S, sarsNumber: null, proofOfResidenceStatus: O,
    hasMathematicsMatric: null, hasMathematicsMajor: null,
    comments: 'Honours B.Ed Educational Management, UNISA (2013).',
  },
];

async function main() {
  const existing = await p.teacherRecruitment.count({ where: { schoolId: SCHOOL_ID } });
  if (existing > 0) {
    console.log(`${existing} recruitment records already exist — checking for new entries only`);
  }

  let created = 0, skipped = 0;

  for (const t of TEACHERS) {
    const already = await p.teacherRecruitment.findFirst({
      where: { schoolId: SCHOOL_ID, lastName: t.lastName, initials: t.initials }
    });
    if (already) {
      console.log(`  SKIP  ${t.lastName} ${t.initials} (${t.school})`);
      skipped++;
      continue;
    }

    await p.teacherRecruitment.create({
      data: {
        schoolId:               SCHOOL_ID,
        lastName:               t.lastName,
        firstName:              t.firstName,
        initials:               t.initials,
        idNumber:               t.idNumber,
        gender:                 t.gender,
        raceGroup:              t.raceGroup,
        phone:                  t.phone,
        email:                  t.email,
        postAppliedFor:         t.postAppliedFor,
        subjectSpecialization:  t.subjectSpecialization,
        applicationDate:        t.applicationDate,
        status:                 'APPLIED',
        cvStatus:               t.cvStatus,
        saceCertStatus:         t.saceCertStatus,
        saceNumber:             t.saceNumber,
        matricCertStatus:       t.matricCertStatus,
        qualCertStatus:         t.qualCertStatus,
        bankLetterStatus:       t.bankLetterStatus,
        sarsDocStatus:          t.sarsDocStatus,
        sarsNumber:             t.sarsNumber,
        proofOfResidenceStatus: t.proofOfResidenceStatus,
        hasMathematicsMatric:   t.hasMathematicsMatric,
        hasMathematicsMajor:    t.hasMathematicsMajor,
        comments:               t.comments
          ? `${t.comments} | Attached school: ${t.school}`
          : `Attached school: ${t.school}`,
      }
    });
    console.log(`  ADDED ${t.lastName} ${t.initials} — ${t.school}${t.firstName ? ` (${t.firstName})` : ' (first name TBD)'}`);
    created++;
  }

  console.log(`\nDone. Created: ${created}, Skipped: ${skipped}`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => p.$disconnect());
